# Generated by Django 3.0.7 on 2020-07-29 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_docstring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='modified',
            field=models.DateTimeField(null=True),
        ),
    ]
